version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www
      - /var/www/vendor
    environment:
      - APP_ENV=local
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3

  vite:
    build: .
    container_name: laravel-vite
    command: npm run dev
    volumes:
      - .:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"
    depends_on:
      app:
        condition: service_healthy
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
      - "5173:5173"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      app:
        condition: service_healthy
      vite:
        condition: service_started
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge