version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projeto
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["/bin/bash", "/var/www/entrypoints.sh"]
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: projeto-nginx
    ports:
      - "8080:80"
      - "5173:5173"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge