services:
  app:
    build:
      context: .
    ports:
      - "8080:8080" 
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"  # Porta 3307 no host, para evitar conflito
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql-data:

networks:
  laravel:
    driver: bridge
