version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: laravel-app
    volumes:
      - .:/var/www
      - node_modules_data:/var/www/node_modules
    environment:
      - APP_ENV=local
      - COMPOSER_MEMORY_LIMIT=-1
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - laravel_network
    expose:  # 👈 Add this to expose port 9000 for PHP-FPM
      - "9000"
    healthcheck:  # 👈 Healthcheck configuration
      test: ["CMD-SHELL", "fcgi-ping localhost:9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s  
    command: >
      sh -c "
      mkdir -p storage/framework/{cache,sessions,views} storage/logs bootstrap/cache &&
      composer install --no-interaction --prefer-dist --optimize-autoloader &&
      ([ -f .env ] || (cp .env.example .env && php artisan key:generate --ansi)) &&
      php artisan config:clear &&
      php artisan view:clear &&
      php artisan route:clear &&
      php artisan cache:clear &&
      php artisan storage:link &&
      php-fpm -F -R -y /usr/local/etc/php-fpm.conf  # 👈 Explicitly specify PHP-FPM config
      "

  vite:
    image: node:18
    container_name: laravel-vite
    working_dir: /var/www
    volumes:
      - node_modules_data:/var/www/node_modules
    ports:
      - "5173:5173"
    environment:
      - APP_ENV=local
    command: >
      sh -c "
      npm install &&
      npm run dev -- --host
      "
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel_network

volumes:
  vendor_data:
  node_modules_data:

networks:
  laravel_network:
    driver: bridge