version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    networks:
      - laravel_network
    depends_on:
      vite:
        condition: service_started

  vite:
    image: node:18
    container_name: laravel-vite
    working_dir: /var/www
    volumes:
      - .:/var/www
      - vite_node_modules:/var/www/node_modules
    ports:
      - "5173:5173"
    environment:
      - APP_ENV=local
    command: >
      sh -c "npm install && npm run dev -- --host"
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      app:
        condition: service_started
    networks:
      - laravel_network

volumes:
  vite_node_modules:

networks:
  laravel_network:
    driver: bridge