services:
  app:
    build: 
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: laravel-app
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    networks:
      - laravel_network
    depends_on:
      vite:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    container_name: laravel-vite
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vite_node_modules:/var/www/node_modules
    environment:
      - APP_ENV=local
      - VITE_APP_URL=http://localhost
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173 || [ -f public/hot ] || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      app:
        condition: service_started
    networks:
      - laravel_network

volumes:
  vite_node_modules:

networks:
  laravel_network:
    driver: bridge