version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    networks:
      - laravel_network
    depends_on:
      vite:
        condition: service_started

  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    container_name: laravel-vite
    working_dir: /var/www
    volumes:
      - .:/var/www
      - vite_node_modules:/var/www/node_modules
    ports:
      - "5173:5173"
      - "24678:24678" # Porta do HMR
    environment:
      - APP_ENV=local
      - VITE_APP_URL=http://localhost
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      app:
        condition: service_started
    networks:
      - laravel_network

volumes:
  vite_node_modules:  # Volume corretamente declarado

networks:
  laravel_network:
    driver: bridge