version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "php", "/var/www/artisan", "inspire"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s  

  vite:
    image: node:18
    container_name: laravel-vite
    working_dir: /var/www
    command: >
      sh -c "
      npm install && 
      if [ \"$APP_ENV\" = 'production' ]; then
        npm run build
      else
        npm run dev -- --host
      fi
      "
    volumes:
      - .:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"
    environment:
      - APP_ENV=${APP_ENV:-local}
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      app:
        condition: service_healthy
    networks:
    - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      app:
        condition: service_healthy
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge