version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "php", "/var/www/artisan", "inspire"]
      interval: 10s
      timeout: 5s
      retries: 3

  vite:
    image: node:18
    container_name: laravel-vite
    working_dir: /var/www
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"
    environment:
        - APP_ENV=local
        - RUN_MIGRATIONS=true
        - SEED_DATABASE=false
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
    depends_on:
      app:
        condition: service_healthy
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      app:
        condition: service_healthy
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge