version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: laravel-app
    volumes:
      - .:/var/www
      - node_modules_data:/var/www/node_modules
    environment:
      - APP_ENV=local
      - COMPOSER_MEMORY_LIMIT=-1
      - HOST_UID=${UID:-1000}
      - HOST_GID=${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - laravel_network
    expose:
      - "9000"
    healthcheck:
      test: ["CMD-SHELL", "fcgi-ping localhost:9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  vite:
    image: node:18
    container_name: laravel-vite
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"
      - "24678:24678"  # Porta do HMR
    environment:
      - APP_ENV=local
      - VITE_APP_URL=http://localhost:5173
    command: >
      sh -c "
      npm install &&
      npm run dev -- --host
      "
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel_network

volumes:
  vendor_data:
  node_modules_data:

networks:
  laravel_network:
    driver: bridge