version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    networks:
      - laravel_network
    user: "0:0"  # Garante que permissões funcionem em qualquer sistema
    healthcheck:
      test: ["CMD-SHELL", "[ -f .env ] && [ -f vendor/autoload.php ] && php-fpm -t"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  vite:
    image: node:18
    container_name: laravel-vite
    working_dir: /var/www
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/var/www
      - ./node_modules:/var/www/node_modules
    ports:
      - "5173:5173"
    environment:
      - DOCKER=true
    depends_on:
      app:
        condition: service_healthy
    networks:
      - laravel_network

  nginx:
    build:
      context: ./docker/nginx
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      app:
        condition: service_healthy
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge